name: Typefully with OpenAI on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 16

      - name: OpenAI
        uses: riccardolinares/openai-commit@v0.0.1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-prompt: "Write a description about this git commit: \n${{ github.event.head_commit.message }}"
        id: openai

      - name: Typefully
        uses: riccardolinares/typefully@v0.0.1
        with:
          typefully-api-key: ${{ secrets.TYPEFULLY_API_KEY }}
          content: ${{ steps.openai.outputs.text }}
